global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'entitlements-service'
    static_configs:
      - targets: ['entitlements-service:8000']

  - job_name: 'telemetry-service'
    static_configs:
      - targets: ['telemetry-service:8001']
