apiVersion: v1
kind: Service
metadata:
  name: entitlements-service
  namespace: production
spec:
  selector:
    app: entitlements
  ports:
    - protocol: TCP
      port: 80        # Port exposed by the service
      targetPort: 8000 # Port the container is listening on
  type: ClusterIP
